const speed = 5;
const keysPressed = [];
const keyLeft = 65;
const keyRight = 68;
const keyUp = 87;
const keyDown = 83;
const keyEnter = 13;
const keyEsc = 27;
const keys = [keyLeft, keyRight, keyUp, keyDown];