
const SpriteList = [
	// 'Albert.png',
	'astronomer.png',
	'babies_mother.png',
	'bartender.png',
	'big_momma.png',
	'Captain.png',
	'chef.png',
	'ChrisRock.png',
	'Darryl.png',
	// 'Doggy.png',
	'drunkard0.png',
	'drunkard1.png',
	'Faelon.png',
	'Farmer.png',
	'fat_old_guy.png',
	// 'geisha.png',
	// 'Goblin.png',
	'Guard.png',
	'Gunnar.png',
	// 'guy_world.png',
	// 'Kamwerere.png',
	// 'King.png',
	// 'Kitty.png',
	// 'lady.png',
	// 'Mate.png',
	// 'Mel.png',
	// 'mokkan.png',
	// 'Mom.png',
	// 'prisoner.png',
	// 'ring_bearer.png',
	// 'Rios.png',
	// 'SallyJones.png',
	// 'Seaside_informant.png',
	// 'sensei.png',
	// 'shyzu_female.png',
	// 'shyzu_male.png',
	// 'soldier.png',
	// 'Tiggy.png',
	// 'Tipper.png',
	// 'toddler.png',
	// 'Trent.png',
	// 'villager1.png',
	// 'villager2.png',
	// 'villager3.png',
	// 'villager4.png',
	// 'villager5.png',
	// 'villager6.png',
	// 'villager7.png',
];
